parameters:
#    rdg_soccer.example.class: Rdg\SoccerBundle\Example

services:
#    rdg_soccer.example:
#        class: %rdg_soccer.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
